### ISSUE TITLE
logInvalidPath is not defined

### ISSUE THREAD

**Issue by DARKSETH23** [FrenchYann/JSON_for_construct2#7]
Hi Yann,

i have 2 pc's:

1.   C2-r250 with Json-1.1
2.   C2-r250 with Json-1.2

on pc 1 i have exported with no issues
on pc 2 same project:
  -  at runtime, when i am trying to do a local storage get for a Json object. i get the following console error:

Uncaught ReferenceError: logInvalidPath is not defined
________________________________________

Now, if I understand correctly it is saying that your function logInvalidPath itself is not defined within the plugin.

I had a look through your 1.2/runtime.js and found no syntax errors:

function logInvalidPath(path) {
      log("invalid path: root@"+ path.toString(),"warn");
      console.trace();
}
________________________________________

As I said, 1.1 doesn't give me that issue, and I know it doesn't have that function at all.
Maybe have a look, and let us know if you do a new release.

Thanks for the awesome plugin, you rock man!

Here is the log below:

![jsonbug](https://user-images.githubusercontent.com/16702914/35563946-292336fe-05c1-11e8-8a48-fa224840f4e2.png)

**Comment by FrenchYann** [comment]
Looks like it has something to do with minification.
Some issues had piled up without me noticing them... I'll try to solve all that as soon as I can.
Thanks.

**Comment by FrenchYann** [comment]
Found the problem, logInvalidPath was indeed removed on export because it's between the `/**BEGIN-PREVIEWONLY**/` and `/**END-PREVIEWONLY**/` in runtime.js
It being removed is ok, since it's supposed to be a debugging function, but since it's still called, I decided to add an empty version before. 
At preview time, it'll use the one defined in the `PREVIEWONLY` section, and after export the empty function will be used. 
I think this solution is better than sprinkling some `if(typeof cr_is_preview !== "undefined")` before each call.
