### ISSUE TITLE
Get value from arbitrary depth

### ISSUE THREAD

**Issue by Lamby777** [FrenchYann/JSON_for_construct2#8]
Given the fact Construct 2 doesn't support the spread operator like JavaScript does, I can't find a way to get something like `JSON.Value(0, "foo.bar")` to return the value `"Hello World`", assuming the currently loaded object is
```
{
    foo: {
        bar: "Hello World"
    }
}
```

The problem is that I can't just write `JSON.Value(0, "foo", "bar")`, because the function I'm writing needs to be able to accept keys with any number of dots in them, and this solution won't work if the key has 2 dots or none. I've seen this done in lodash before, is there a feature like that with this plugin?

**Comment by Lamby777** [comment]
If anyone's here looking for a solution, this is a pretty terrible workaround that only works for finite object depth, but it's better than nothing.



![image](https://user-images.githubusercontent.com/35111165/184583553-622bc85f-7891-4ac9-b6d0-29140e87d2e4.png)
![image](https://user-images.githubusercontent.com/35111165/184583654-4ac1ffdf-d6ce-426f-8aa0-38a9113e1bd5.png)

**Comment by FrenchYann** [comment]
It's been years since I did anything in construct and I can't install it on my pc 'cause I'm on linux.
But if memory serves right, you should be able to loop through your tokens using tokencount and tokenat, and for each token you can use the Set Current Path action to change the relative path of the JSON object 

I don't remember exactly what's in it, but this may also give you some inspiration
https://github.com/FrenchYann/JSON_for_construct2#inspecting-an-unknown-json

**Comment by Lamby777** [comment]
Wow, I completely underestimated how useful the relative path feature could be. Thanks!

![image](https://user-images.githubusercontent.com/35111165/184998205-efe1b618-486e-4311-bc6a-171817ff172e.png)
